"""Initial schema with TimescaleDB hypertables

Revision ID: 920df5c66454
Revises: 
Create Date: 2025-11-10 15:25:04.694206

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '920df5c66454'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_predictions',
    sa.Column('prediction_id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.Column('input_features', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('output', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.Column('ground_truth', sa.Float(), nullable=True),
    sa.Column('error', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('prediction_id')
    )
    op.create_index(op.f('ix_model_predictions_model_name'), 'model_predictions', ['model_name'], unique=False)
    op.create_index(op.f('ix_model_predictions_timestamp'), 'model_predictions', ['timestamp'], unique=False)
    op.create_table('sessions',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('device_info', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('total_samples', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('active_classifiers', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('active_streams', sa.ARRAY(sa.String()), nullable=True),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.create_table('events',
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('event_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.session_id'], ),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index(op.f('ix_events_timestamp'), 'events', ['timestamp'], unique=False)
    op.create_table('feature_vectors',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('frontal_theta', sa.Float(), nullable=True),
    sa.Column('frontal_beta', sa.Float(), nullable=True),
    sa.Column('parietal_alpha', sa.Float(), nullable=True),
    sa.Column('theta_beta_ratio', sa.Float(), nullable=True),
    sa.Column('theta_alpha_ratio', sa.Float(), nullable=True),
    sa.Column('all_features', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.session_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feature_vectors_timestamp'), 'feature_vectors', ['timestamp'], unique=False)
    op.create_table('predictions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=False),
    sa.Column('classifier_name', sa.String(length=100), nullable=False),
    sa.Column('workload', sa.Float(), nullable=True),
    sa.Column('attention', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('features', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('processing_time_ms', sa.Float(), nullable=True),
    sa.Column('classifier_version', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.session_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_predictions_session_id'), 'predictions', ['session_id'], unique=False)
    op.create_index(op.f('ix_predictions_timestamp'), 'predictions', ['timestamp'], unique=False)
    op.create_index(op.f('ix_predictions_user_id'), 'predictions', ['user_id'], unique=False)
    op.create_table('stream_samples',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('stream_name', sa.String(length=100), nullable=False),
    sa.Column('stream_type', sa.String(length=50), nullable=True),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.session_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stream_samples_stream_name'), 'stream_samples', ['stream_name'], unique=False)
    op.create_index(op.f('ix_stream_samples_timestamp'), 'stream_samples', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stream_samples_timestamp'), table_name='stream_samples')
    op.drop_index(op.f('ix_stream_samples_stream_name'), table_name='stream_samples')
    op.drop_table('stream_samples')
    op.drop_index(op.f('ix_predictions_user_id'), table_name='predictions')
    op.drop_index(op.f('ix_predictions_timestamp'), table_name='predictions')
    op.drop_index(op.f('ix_predictions_session_id'), table_name='predictions')
    op.drop_table('predictions')
    op.drop_index(op.f('ix_feature_vectors_timestamp'), table_name='feature_vectors')
    op.drop_table('feature_vectors')
    op.drop_index(op.f('ix_events_timestamp'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_model_predictions_timestamp'), table_name='model_predictions')
    op.drop_index(op.f('ix_model_predictions_model_name'), table_name='model_predictions')
    op.drop_table('model_predictions')
    # ### end Alembic commands ###
